import { InventoryItem, Vendor, PurchaseOrder, CatalogueEntry } from "./types";

export const SEED_INVENTORY: InventoryItem[] = [
  {
    sku: "Ele/Mod/0001",
    name: "3 Module Box",
    category: "Electrical",
    subCategory: "Module",
    unit: "NOS",
    openingStock: 87,
    liveStock: 225,
    condition: "New",
  },
  {
    sku: "Con/Cem/0321",
    name: "Cement",
    category: "Construction",
    subCategory: "Cement",
    unit: "BAG",
    openingStock: 3807,
    liveStock: 4300,
    condition: "New",
  },
  {
    sku: "Pvc/Pip/0073",
    name: "PVC Pipe 75MM",
    category: "PVC",
    subCategory: "Pipe",
    unit: "FEET",
    openingStock: 740,
    liveStock: 2770,
    condition: "New",
  },
  {
    sku: "Oil/Die/0419",
    name: "Diesel",
    category: "Oil",
    subCategory: "Diesel",
    unit: "LTR",
    openingStock: 0,
    liveStock: 669,
    condition: "New",
  },
  {
    sku: "Fir/Pip/0476",
    name: "Fire Pipe 1in",
    category: "Fire",
    subCategory: "Pipe",
    unit: "FEET",
    openingStock: 0,
    liveStock: 1520,
    condition: "New",
  },
  {
    sku: "Har/Bol/0049",
    name: "Tower Bolt 12in",
    category: "Hardware",
    subCategory: "Bolt",
    unit: "NOS",
    openingStock: 33,
    liveStock: 36,
    condition: "New",
  },
  {
    sku: "San/Jal/0034",
    name: "4in Plane Jali",
    category: "Sanitary",
    subCategory: "Jali",
    unit: "NOS",
    openingStock: 20,
    liveStock: 23,
    condition: "New",
  },
  {
    sku: "Sca/Pip/0001",
    name: "Scaffolding Pipe 2in",
    category: "Scaffolding",
    subCategory: "Pipe",
    unit: "NOS",
    openingStock: 200,
    liveStock: 60,
    condition: "Good",
  },
  {
    sku: "Sca/Pip/0002",
    name: "Scaffolding Clamp",
    category: "Scaffolding",
    subCategory: "Clamp",
    unit: "NOS",
    openingStock: 500,
    liveStock: 120,
    condition: "Needs Repair",
  },
  {
    sku: "Tmp/Fen/0001",
    name: "Boundary Fencing Panel",
    category: "Temporary",
    subCategory: "Fencing",
    unit: "NOS",
    openingStock: 50,
    liveStock: 35,
    condition: "Needs Repair",
  },
  {
    sku: "MS/Pip/0001",
    name: "MS Pipe 2in",
    category: "MS",
    subCategory: "Pipe",
    unit: "FEET",
    openingStock: 300,
    liveStock: 45,
    condition: "Damaged",
  },
  {
    sku: "Ele/Tmp/0001",
    name: "Temporary Wiring Cable",
    category: "Electrical",
    subCategory: "Cable",
    unit: "MTR",
    openingStock: 500,
    liveStock: 200,
    condition: "Good",
  },
  {
    sku: "Ele/Wir/0007",
    name: "4 SQMM Black Wire",
    category: "Electrical",
    subCategory: "Wire",
    unit: "COIL",
    openingStock: 0,
    liveStock: 0,
    condition: "New",
  },
  {
    sku: "Con/Bri/0627",
    name: "Kakka Bricks",
    category: "Construction",
    subCategory: "Bricks",
    unit: "NOS",
    openingStock: 20025,
    liveStock: 0,
    condition: "New",
  },
  {
    sku: "Tmp/Off/0001",
    name: "Temp Office Partition",
    category: "Temporary",
    subCategory: "Office",
    unit: "NOS",
    openingStock: 10,
    liveStock: 8,
    condition: "Good",
  },
];

export const SEED_CATALOGUE: CatalogueEntry[] = [
  {
    sku: "Ele/Mod/0001",
    brand: "Havells",
    specs: "3 Module, Polycarbonate",
    location: "Rack A1",
    minStock: 100,
    image: "",
    status: "Approved",
  },
  {
    sku: "Con/Cem/0321",
    brand: "Ultratech",
    specs: "OPC 53 Grade",
    location: "Warehouse 1",
    minStock: 500,
    image: "",
    status: "Approved",
  },
];

export const SEED_VENDORS: Vendor[] = [
  {
    id: "V001",
    name: "Shree Cement Ltd",
    contact: "Rajesh Kumar",
    phone: "9826123456",
    category: "Construction",
    gst: "23AAAAA0000A1Z5",
    status: "Active",
  },
  {
    id: "V002",
    name: "Havells Distributor",
    contact: "Amit Jain",
    phone: "9754321098",
    category: "Electrical",
    gst: "23BBBBB0000B1Z5",
    status: "Active",
  },
  {
    id: "V003",
    name: "HP Petrol Pump",
    contact: "Suresh",
    phone: "9300112233",
    category: "Oil",
    gst: "23CCCCC0000C1Z5",
    status: "Active",
  },
  {
    id: "V004",
    name: "Gwalior Hardware",
    contact: "Pradeep",
    phone: "9425567890",
    category: "Hardware",
    gst: "23DDDDD0000D1Z5",
    status: "Active",
  },
  {
    id: "V005",
    name: "MP Pipes & Fittings",
    contact: "Vikram Singh",
    phone: "9981234567",
    category: "Plumbing",
    gst: "23EEEEE0000E1Z5",
    status: "Active",
  },
];

export const SEED_POS: PurchaseOrder[] = [
  {
    id: "PO-2026-001",
    project: "Garden City Villa",
    phase: "Phase 1",
    workType: "Civil",
    milestone: "Foundation",
    vendor: "Shree Cement Ltd",
    items: [
      {
        sku: "Con/Cem/0321",
        name: "Cement",
        qty: 500,
        unit: "BAG",
        rate: 380,
        gstPct: 28,
        total: 190000,
        totalWithGST: 243200,
      },
    ],
    totalValue: 190000,
    status: "Approved",
    approvalL1: "Approved",
    approvalL2: "Approved",
    createdBy: "Project Manager",
    date: "2026-01-10",
  },
  {
    id: "PO-2026-002",
    project: "Eden Garden",
    phase: "Phase 2",
    workType: "Electrical",
    milestone: "Slab",
    vendor: "Havells Distributor",
    items: [
      {
        sku: "Ele/Mod/0001",
        name: "3 Module Box",
        qty: 100,
        unit: "NOS",
        rate: 180,
        gstPct: 18,
        total: 18000,
        totalWithGST: 21240,
      },
    ],
    totalValue: 18000,
    status: "Approved",
    approvalL1: "N/A",
    approvalL2: "N/A",
    createdBy: "Project Manager",
    date: "2026-01-12",
  },
  {
    id: "PO-2026-003",
    project: "Zen Garden",
    phase: "Phase 1",
    workType: "Plumbing",
    milestone: "Structure",
    vendor: "MP Pipes & Fittings",
    items: [
      {
        sku: "Pvc/Pip/0073",
        name: "PVC Pipe 75MM",
        qty: 1000,
        unit: "FEET",
        rate: 45,
        gstPct: 18,
        total: 45000,
        totalWithGST: 53100,
      },
    ],
    totalValue: 45000,
    status: "Pending L1",
    approvalL1: "Pending",
    approvalL2: "Pending",
    createdBy: "Project Manager",
    date: "2026-01-15",
  },
];

export const PROJECTS = [
  "Garden City Villa",
  "Eden Garden",
  "Zen Garden",
  "Marriott Hotel",
  "Hyde Park",
  "Wildflower",
  "Westgate",
  "Neo Meridian",
  "Marigold",
  "One Business Center",
  "Regal Garden Apartment",
  "Regal Garden Villa",
  "Other",
];

export const WORK_TYPES = [
  "Civil",
  "Electrical",
  "Plumbing",
  "Painting",
  "Finishing",
  "Landscaping",
  "MEP",
  "Interior",
  "Structure / RCC",
];

export const CATEGORIES = [
  "Electrical",
  "Sanitary",
  "PVC",
  "CPVC",
  "Construction",
  "Hardware",
  "GI",
  "Chemical",
  "Painting",
  "Miscellaneous",
  "UPVC",
  "Brass",
  "HDPE",
  "Oil",
  "Fire",
  "Furniture",
  "Machinery",
  "Camera",
  "Cleaning",
  "Cloth",
  "DWC",
  "Drip Irrigation",
  "MS",
  "Plant",
  "RCC",
  "Scaffolding",
  "Stationary",
  "Stone",
  "Tiles",
  "Temporary",
  "Wooden",
];

export const UNITS = [
  "NOS",
  "LTR",
  "BOX",
  "KGS",
  "FEET",
  "MTR",
  "PKT",
  "SQF",
  "SET",
  "COIL",
  "BDL",
  "BAG",
  "BKT",
  "Pair",
  "RFT",
  "CFT",
  "CUM",
  "TON",
  "ROL",
  "Bottle",
  "DRUM",
  "Sheet",
  "SQM",
  "LOT",
  "CBM",
  "CRAN",
  "RIM",
  "Katte",
];
